### ISSUE TITLE
Unable to install plugins using provided documentation

### ISSUE THREAD

**Issue by maticmeznar** [sensu-plugins/documentation#3]
I've been following the instructions on:
https://github.com/sensu-plugins/documentation/blob/master/user_docs/installation_instructions.md

and I've been unable to install "sensu-plugins-disk-checks" in the example. Neither was I able to install "sensu-plugins-network-check"

`/opt/sensu/embedded/bin/gem install sensu-plugins-disk-checks -P MediumSecurity`
`EROR:  While executing gem ... (Gem::Security::Exception)    missing signing certificate`

`/opt/sensu/embedded/bin/gem install sensu-plugins-network-check -P MediumSecurity`
`ERROR:  Could not find a valid gem 'sensu-plugins-network-check' (>= 0) in any repository`

`/opt/sensu/embedded/bin/gem cert --list`
`/CN=mattjones/DC=yieldbot/DC=com`

I'm using CentOS 7.1

**Comment by mattyjones** [comment]
@maticmeznar 
`/opt/sensu/embedded/bin/gem install sensu-plugins-network-check -P MediumSecurity
ERROR: Could not find a valid gem 'sensu-plugins-network-check' (>= 0) in any repository`

The plugin is `sensu-plugins-network-checks`  You were missing the `s` ;p

As to the sensu-plugins-disk-checks issue

```
    mjones@Matts-MacBook-Pro-2.local:~/Projects/personal$ gem install sensu-plugins-disk-checks -P MediumSecurity
    Fetching: sensu-plugins-disk-checks-0.0.4.gem (100%)
    ERROR:  While executing gem ... (Gem::Security::Exception)
        root cert /CN=mattjones/DC=yieldbot/DC=com is not trusted
    mjones@Matts-MacBook-Pro-2.local:~/Projects/personal$ gem cert --add <(curl -Ls https://raw.githubusercontent.com/sensu-plugins/sensu-plugins.github.io/master/certs/sensu-plugins
.pem)
    Added '/CN=mattjones/DC=yieldbot/DC=com'
    mjones@Matts-MacBook-Pro-2.local:~/Projects/personal$ gem install sensu-plugins-disk-checks -P MediumSecurity
    You can use the embedded Ruby by setting EMBEDDED_RUBY=true in /etc/default/sensu
    Successfully installed sensu-plugins-disk-checks-0.0.4
    Parsing documentation for sensu-plugins-disk-checks-0.0.4
    Installing ri documentation for sensu-plugins-disk-checks-0.0.4
    Done installing documentation for sensu-plugins-disk-checks after 0 seconds
    1 gem installed
```

I am on OSX but I also tested this against Cent6 and ubuntu14.  I don't have a Cent7 box at them moment, if the above steps or docs don't work let me know and I will spin up a Cent7 box and figure it out.

Thanks!

**Comment by maticmeznar** [comment]
In https://github.com/sensu-plugins/documentation/blob/master/user_docs/installation_instructions.md , section "Standard Installation" it says: "gem install sensu-plugin-disk-checks". The valid gem name is "sensu-pluginS-disk-checks". It says properly later on in the instructions, but the first mention is incorrect.

Also, to run the check from command line, I have to type "/opt/sensu/embedded/bin/ruby /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-disk-checks-0.0.4/bin/check-disk-usage.rb" and not "/opt/sensu/embedded/bin/ruby check-disk-usage.rb".

Should I be using Sensu's embedded ruby or the OS provided one?

**Comment by mattyjones** [comment]
@maticmeznar this was due to a binstubs issue that has since been corrected

**Comment by majormoses** [comment]
I have installed many sensu gems with no issue since then so I assume this is a stale issue.
