### ISSUE TITLE
Update FAQ with ruby EOL version

### ISSUE THREAD

**Issue by nathanhruby** [sensu-plugins/documentation#7]
The [FAQ](docs/FAQ.md) currently lists the last supported EOL version of Ruby as 1.9.3:
> We will target the latest the EOL Ruby, currently that is 1.9.3.

Can the mentioned version be updated to 2.0.0 as per [the Ruby docs](https://www.ruby-lang.org/en/downloads/branches/)?  

The current 1.9.3 statement on the FAQ page is confusing for people who don't spend a lot of time in the Ruby ecosystem but sometimes want to contribute back to the plugins.  It's hard to know what to do with build/test failures.

**Comment by majormoses** [comment]
@nathanhruby yes we should update that, can you PR this?

**Comment by majormoses** [comment]
@nathanhruby we have updated this and clarified our stance to support non EOL versions and will attempt to have `EOL.max` but in cases where you need to break compatibility for a justifiable reason it is ok in a major release of the gem. This should not really be an issue really as people should be using the embedded ruby in sensu and we will certainly keep these versions in mind when dropping version support.
